"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useOperations } from "../../components/operations-provider";
import { AdminPageHeader, formatCurrency, paymentMethodLabels } from "../../components/ui";
import { formatGuestName } from "../../lib/operations";
import type { PaymentMethod } from "../../lib/types";

export default function NewPaymentPage() {
  const router = useRouter(); const searchParams = useSearchParams(); const { state, addPayment } = useOperations(); const eligible = useMemo(() => state.reservations.filter((item) => item.balance > 0), [state.reservations]);
  const requested = eligible.find((item) => item.id === searchParams.get("reservation"));
  const [form, setForm] = useState({ reservationId: requested?.id ?? eligible[0]?.id ?? "", amount: requested?.balance ?? eligible[0]?.balance ?? 0, method: "cash" as PaymentMethod, reference: "", note: "" }); const [error, setError] = useState("");
  const selected = eligible.find((item) => item.id === form.reservationId); const guest = state.guests.find((item) => item.id === selected?.primaryGuestId);
  function choose(value: string) { const reservation = eligible.find((item) => item.id === value); setForm({ ...form, reservationId: value, amount: reservation?.balance ?? 0 }); }
  function submit(event: FormEvent) { event.preventDefault(); try { addPayment(form); router.push("/admin/pagos/pendientes?created=payment"); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible registrar el pago."); } }
  return <><AdminPageHeader eyebrow="Movimiento manual" title="Registrar pago" description="Guarda un cobro interno y recalcula automáticamente pagado y saldo." /><div className="admin-operation-layout"><form className="admin-form-card" onSubmit={submit}><div className="admin-field-grid"><label className="admin-field--full">Reserva<select value={form.reservationId} onChange={(e) => choose(e.target.value)}><option value="">Seleccionar</option>{eligible.map((item) => { const person = state.guests.find((guestItem) => guestItem.id === item.primaryGuestId); return <option value={item.id} key={item.id}>{item.code} · {person ? formatGuestName(person.firstName, person.lastName) : "Sin huésped"} · saldo {formatCurrency(item.balance)}</option>; })}</select></label><label>Importe<input min="100" max={selected?.balance} step="100" type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} /></label><label>Medio<select value={form.method} onChange={(e) => setForm({ ...form, method: e.target.value as PaymentMethod })}>{Object.entries(paymentMethodLabels).filter(([key]) => !["mercado_pago", "card"].includes(key)).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Referencia <small>opcional</small><input value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} /></label><label className="admin-field--full">Observación <small>opcional</small><textarea rows={3} value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label></div>{error ? <p className="admin-form-error">{error}</p> : null}<button className="admin-button admin-button--primary admin-button--large" disabled={!selected} type="submit">Registrar pago</button></form><aside className="admin-form-summary"><p>Reserva seleccionada</p><h2>{guest ? formatGuestName(guest.firstName, guest.lastName) : "Sin selección"}</h2>{selected ? <dl><div><dt>Total</dt><dd>{formatCurrency(selected.total)}</dd></div><div><dt>Pagado</dt><dd>{formatCurrency(selected.paid)}</dd></div><div><dt>Saldo actual</dt><dd>{formatCurrency(selected.balance)}</dd></div><div><dt>Saldo posterior</dt><dd>{formatCurrency(Math.max(selected.balance - form.amount, 0))}</dd></div></dl> : null}</aside></div></>;
}
