import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { lodgingRateSchema, lodgingRequestSchema, holdSettingsSchema, holdInputSchema, sourceSchema, specialDateSchema, lodgingRpcArgs, lodgingRequestOrigin, lodgingError, emptyLodgingSnapshot } from "../app/lib/lodging.ts";
import { roomTypeInputSchema } from "../app/admin/data/configuration-validation.ts";

const request = { checkIn: "2027-01-04", checkOut: "2027-01-06", adults: 2, children: 0 };
const rate = { categoryId: "40000000-0000-4000-8000-000000000001", name: "Synthetic rate", kind: "day", dayKind: "normal", weekdays: [1,2,3,4], validFrom: "2027-01-01", validUntil: "", amount: 70000, minimumStay: 1, conditions: "", active: true, salesEnabled: true };
test("T2 category request translates to allowlisted RPC arguments",()=>assert.deepEqual(lodgingRpcArgs(lodgingRequestSchema.parse(request)),{p_check_in:request.checkIn,p_check_out:request.checkOut,p_adults:2,p_children:0,p_category:null}));
for(const [label,patch] of [["same-day checkout",{checkOut:request.checkIn}],["inverted dates",{checkOut:"2027-01-03"}],["invalid calendar date",{checkIn:"2027-02-30"}],["more than 60 nights",{checkOut:"2027-06-01"}],["children without adult",{adults:0,children:1}],["negative children",{children:-1}],["fractional adult",{adults:1.5}],["capacity total",{adults:30,children:1}],["unexpected physical room",{roomId:rate.categoryId}]]) test(`T2 request rejects ${label}`,()=>assert.equal(lodgingRequestSchema.safeParse({...request,...patch}).success,false));
test("T2 daily rate accepts configured weekdays without inventing Sunday",()=>assert.deepEqual(lodgingRateSchema.parse(rate).weekdays,[1,2,3,4]));
for(const [label,patch] of [["empty weekdays",{weekdays:[]}],["duplicate days",{weekdays:[1,1]}],["zero price",{amount:0}],["negative price",{amount:-1}],["fractional cents",{amount:1.001}],["unbounded promotion",{kind:"promotion",conditions:"Synthetic"}],["promotion without conditions",{kind:"promotion",validUntil:"2027-01-10"}],["multi-date override",{kind:"override",validUntil:"2027-01-10"}],["disabled rule selling",{active:false}],["invalid day specificity",{dayKind:"any"}],["inverted validity",{validUntil:"2026-12-31"}],["price by person",{perPerson:true}]]) test(`T2 tariff rejects ${label}`,()=>assert.equal(lodgingRateSchema.safeParse({...rate,...patch}).success,false));
test("T2 explicitly configured Sunday accepted without official default",()=>assert.equal(lodgingRateSchema.safeParse({...rate,weekdays:[7],amount:12345}).success,true));
test("T2 bounded promotion and override supported",()=>{assert.equal(lodgingRateSchema.safeParse({...rate,kind:"promotion",validUntil:"2027-01-10",conditions:"Synthetic dated conditions"}).success,true);assert.equal(lodgingRateSchema.safeParse({...rate,kind:"override",validUntil:rate.validFrom}).success,true);});
test("T2 exact configured special-date taxonomy",()=>{for(const kind of ["HOLIDAY","SPECIAL","NORMAL_OVERRIDE"])assert.equal(specialDateSchema.safeParse({date:"2027-01-01",kind,name:"Synthetic",active:true}).success,true); assert.equal(specialDateSchema.safeParse({date:"2027-01-01",kind:"auto",name:"Synthetic",active:true}).success,false);});
test("T2 configurable TTL constrained to two hours",()=>{assert.deepEqual(holdSettingsSchema.parse({webMinutes:15,adminMinutes:120}),{webMinutes:15,adminMinutes:120});for(const n of [0,121,-1,1.2]) assert.equal(holdSettingsSchema.safeParse({webMinutes:n,adminMinutes:120}).success,false);});
test("T2 all eight source codes accepted",()=>{for(const source of ["web","whatsapp","phone","walk_in","instagram","referral","admin","other"])assert.equal(sourceSchema.parse(source),source);});
test("T2 public hold does not accept arbitrary payload metadata",()=>assert.equal(holdInputSchema.safeParse({request,token:"not-accepted"}).success,false));
test("T2 unavailable schema produces no demo categories or rates",()=>{const value=emptyLodgingSnapshot();assert.equal(value.schemaReady,false);assert.equal(value.categories.length+value.rates.length+value.specialDates.length,0);});
test("T2 error responses never include database error content",()=>{for(const code of ["42501","23P01","22023","23514","XX000",undefined]){const error=lodgingError(code,"PRIVATE SQL TOKEN");assert.doesNotMatch(error.message,/PRIVATE|SQL|TOKEN/);assert.ok(error.status>=400);}});
test("T2 rate limiting and concurrency have explicit status",()=>{assert.equal(lodgingError("P0001","RATE_LIMITED").status,429);assert.equal(lodgingError("23P01").status,409);});
test("T2 categories can be configured without invented legacy price",()=>assert.equal(roomTypeInputSchema.parse({code:"double",internalName:"Synthetic double",publicName:"Synthetic",description:"",defaultCapacity:2,baseRate:null,active:false}).baseRate,null));
const migration=readFileSync(new URL("../supabase/migrations/20260904160115_lodging_rates_availability_and_holds.sql",import.meta.url),"utf8");
test("T2 migration retains RLS and RPC-only writes",()=>{for(const table of ["lodging_holds","lodging_rate_rules","lodging_special_dates"])assert.ok(migration.includes(`alter table public.${table} enable row level security`));assert.doesNotMatch(migration,/grant\s+(?:all|insert|update|delete).*to\s+anon/i);});
test("T2 migrations have no business seeds outside function bodies",()=>{const outer=migration.replace(/as \$\$[\s\S]*?\$\$;/g,"");assert.doesNotMatch(outer,/insert into (?:auth\.|public\.(?:rooms|room_types|guests|reservations|payments|lodging_rate_rules|lodging_special_dates|lodging_holds))/i);assert.doesNotMatch(outer,/60000|70000|85000|110000/);});
test("T2 holds share existing calendar lock and use half-open ranges",()=>{assert.match(migration,/hashtextextended\(new\.room_id::text,0\)/);assert.match(migration,/exclude using gist \(room_id with =,stay with &&\)/);assert.match(migration,/expires_at>clock_timestamp\(\)/);assert.match(migration,/for update skip locked/);});
test("T2 public boundary uses HTTP-only cookie, no tokens in URLs",()=>{const route=readFileSync(new URL("../app/api/lodging/holds/route.ts",import.meta.url),"utf8");assert.match(route,/randomBytes\(32\)/);assert.match(route,/httpOnly: true/);assert.match(route,/sameSite: "strict"/);assert.doesNotMatch(route,/searchParams|console\./);});
test("T2 API revalidates staff and payloads",()=>{const route=readFileSync(new URL("../app/api/admin/lodging/route.ts",import.meta.url),"utf8");assert.match(route,/lodgingStaff\(permission\)/);assert.match(route,/assertLodgingOrigin/);assert.match(route,/lodgingRateSchema.parse/);});
test("T2 public components contain no fixed official price values",()=>{for(const file of ["app/components/lodging-results.tsx","app/admin/tarifas/rates-console.tsx"]){assert.doesNotMatch(readFileSync(new URL(`../${file}`,import.meta.url),"utf8"),/60000|70000|85000|110000/);}});
test("T2 strict origin supports Next internal hostname normalization",()=>{
  const input={url:"http://localhost:3000/api/admin/lodging",headers:new Headers({host:"127.0.0.1:3000",origin:"http://127.0.0.1:3000"})};
  assert.equal(lodgingRequestOrigin(input)?.origin,"http://127.0.0.1:3000");
});
test("T2 origin rejects missing, malformed, foreign and insecure nonlocal requests",()=>{
  for(const headers of [{host:"local.invalid"},{host:"local.invalid",origin:"null"},{host:"local.invalid",origin:"https://foreign.invalid"},{host:"local.invalid",origin:"http://local.invalid"},{host:"local.invalid",origin:"https://local.invalid","sec-fetch-site":"cross-site"}])assert.equal(lodgingRequestOrigin({url:"https://local.invalid",headers:new Headers(headers)}),null);
});
