"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useOperations } from "../components/operations-provider";
import { AdminPageHeader, formatCurrency, formatDate, StatusPill } from "../components/ui";
import { formatGuestName, nightsBetween } from "../lib/operations";

export default function CheckInPage() {
  const router = useRouter(); const searchParams = useSearchParams(); const { state, checkIn } = useOperations();
  const eligible = useMemo(() => state.reservations.filter((item) => ["confirmed", "partially_paid", "paid"].includes(item.status)), [state.reservations]);
  const requestedId = searchParams.get("reservation");
  const [selectedId, setSelectedId] = useState(() => eligible.some((item) => item.id === requestedId) ? requestedId ?? "" : eligible[0]?.id ?? ""); const [error, setError] = useState("");
  const reservation = eligible.find((item) => item.id === selectedId); const guest = state.guests.find((item) => item.id === reservation?.primaryGuestId); const room = state.rooms.find((item) => item.id === reservation?.roomId);
  function submit(event: FormEvent) { event.preventDefault(); try { if (!reservation) throw new Error("Seleccioná una reserva."); checkIn(reservation.id); router.push("/admin/huespedes/actuales?checked=in"); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible hacer el check-in."); } }
  return <><AdminPageHeader eyebrow="Llegadas" title="Hacer check-in" description="Confirma la llegada real, aloja al huésped y ocupa la habitación asignada." /><div className="admin-operation-layout"><form className="admin-form-card" onSubmit={submit}><label className="admin-select-record">Reserva<select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}><option value="">Seleccionar reserva</option>{eligible.map((item) => { const person = state.guests.find((guestItem) => guestItem.id === item.primaryGuestId); return <option value={item.id} key={item.id}>{item.code} · {person ? formatGuestName(person.firstName, person.lastName) : "Sin huésped"}</option>; })}</select></label>{reservation && guest ? <div className="admin-operation-card"><div className="admin-operation-card__hero"><span>{guest.firstName.slice(0,1)}</span><div><p>Huésped principal</p><h2>{formatGuestName(guest.firstName, guest.lastName)}</h2><a href={`tel:${guest.phone}`}>{guest.phone}</a></div></div><dl><div><dt>Habitación</dt><dd>{room?.displayName ?? "Sin asignar"}</dd></div><div><dt>Fechas</dt><dd>{formatDate(reservation.checkIn)} → {formatDate(reservation.checkOut)}</dd></div><div><dt>Noches</dt><dd>{nightsBetween(reservation.checkIn, reservation.checkOut)}</dd></div><div><dt>Personas</dt><dd>{reservation.guestCount}</dd></div><div><dt>Total</dt><dd>{formatCurrency(reservation.total)}</dd></div><div><dt>Pagado</dt><dd>{formatCurrency(reservation.paid)}</dd></div><div><dt>Saldo</dt><dd>{formatCurrency(reservation.balance)}</dd></div></dl>{reservation.notes ? <blockquote>{reservation.notes}</blockquote> : null}<StatusPill status={reservation.paymentStatus}>{reservation.balance ? "Saldo pendiente" : "Pago completo"}</StatusPill></div> : null}{error ? <p className="admin-form-error">{error}</p> : null}<button className="admin-button admin-button--primary admin-button--large" disabled={!reservation} type="submit">Hacer check-in</button></form><aside className="admin-operation-help"><p>Al confirmar</p><ol><li>La reserva cambia a alojado.</li><li>La habitación cambia a ocupada.</li><li>Se registra fecha, hora y usuario.</li><li>El huésped aparece en alojados actuales.</li></ol><small>El horario estándar de check-in sigue pendiente de configuración.</small></aside></div></>;
}
