"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useOperations } from "../components/operations-provider";
import { AdminPageHeader, formatCurrency, formatDate, StatusPill } from "../components/ui";
import { formatGuestName } from "../lib/operations";

export default function CheckOutPage() {
  const router = useRouter(); const searchParams = useSearchParams(); const { state, checkOut } = useOperations();
  const eligible = useMemo(() => state.reservations.filter((item) => item.status === "accommodated"), [state.reservations]);
  const requestedId = searchParams.get("reservation");
  const [selectedId, setSelectedId] = useState(() => eligible.some((item) => item.id === requestedId) ? requestedId ?? "" : eligible[0]?.id ?? ""); const [confirmDebt, setConfirmDebt] = useState(false); const [error, setError] = useState("");
  const reservation = eligible.find((item) => item.id === selectedId); const guest = state.guests.find((item) => item.id === reservation?.primaryGuestId); const room = state.rooms.find((item) => item.id === reservation?.roomId); const hasDebt = Boolean(reservation?.balance);
  function submit(event: FormEvent) { event.preventDefault(); try { if (!reservation) throw new Error("Seleccioná una estadía."); if (hasDebt && !confirmDebt) throw new Error("Confirmá que el saldo pendiente fue revisado."); checkOut(reservation.id); router.push("/admin/habitaciones?checked=out"); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible hacer el check-out."); } }
  return <><AdminPageHeader eyebrow="Salidas · límite 10:00" title="Hacer check-out" description="Cierra la estadía y envía automáticamente la habitación a limpieza." /><div className="admin-operation-layout"><form className="admin-form-card" onSubmit={submit}><label className="admin-select-record">Estadía alojada<select value={selectedId} onChange={(e) => { setSelectedId(e.target.value); setConfirmDebt(false); }}><option value="">Seleccionar estadía</option>{eligible.map((item) => { const person = state.guests.find((guestItem) => guestItem.id === item.primaryGuestId); return <option value={item.id} key={item.id}>{item.code} · {person ? formatGuestName(person.firstName, person.lastName) : "Sin huésped"}</option>; })}</select></label>{reservation && guest ? <div className="admin-operation-card"><div className="admin-operation-card__hero"><span>{guest.firstName.slice(0,1)}</span><div><p>Huésped principal</p><h2>{formatGuestName(guest.firstName, guest.lastName)}</h2><small>{room?.displayName}</small></div></div><dl><div><dt>Salida prevista</dt><dd>{formatDate(reservation.checkOut)}</dd></div><div><dt>Hora límite</dt><dd>10:00 hs</dd></div><div><dt>Total</dt><dd>{formatCurrency(reservation.total)}</dd></div><div><dt>Pagado</dt><dd>{formatCurrency(reservation.paid)}</dd></div><div><dt>Saldo</dt><dd>{formatCurrency(reservation.balance)}</dd></div></dl>{hasDebt ? <div className="admin-debt-warning"><StatusPill status="alert">Saldo pendiente</StatusPill><strong>Esta estadía todavía tiene {formatCurrency(reservation.balance)} por cobrar.</strong><label><input type="checkbox" checked={confirmDebt} onChange={(e) => setConfirmDebt(e.target.checked)} /> Revisé el saldo y autorizo continuar en este entorno de prueba.</label></div> : <p className="admin-success-note">La estadía no tiene saldo pendiente.</p>}</div> : null}{error ? <p className="admin-form-error">{error}</p> : null}<button className="admin-button admin-button--primary admin-button--large" disabled={!reservation} type="submit">Hacer check-out</button></form><aside className="admin-operation-help"><p>Al confirmar</p><ol><li>El huésped deja de figurar como alojado.</li><li>La reserva pasa a check-out realizado.</li><li>La habitación pasa a pendiente de limpieza.</li><li>Se registra el evento en auditoría.</li></ol></aside></div></>;
}
