"use client";

import { useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useOperations } from "../components/operations-provider";
import { AdminPageHeader, formatCurrency, formatDate, StatusPill } from "../components/ui";
import { formatGuestName } from "../lib/operations";

export default function CheckOutPage() {
  const router = useRouter(); const searchParams = useSearchParams(); const { state, mode, permissions, checkOut } = useOperations();
  const canManage = mode === "demo" || permissions.includes("reservations.manage");
  const eligible = useMemo(() => state.reservations.filter((item) => item.status === "accommodated"), [state.reservations]);
  const requestedId = searchParams.get("reservation");
  const [selectedId, setSelectedId] = useState(() => eligible.some((item) => item.id === requestedId) ? requestedId ?? "" : eligible[0]?.id ?? ""); const [error, setError] = useState("");
  const reservation = eligible.find((item) => item.id === selectedId); const guest = state.guests.find((item) => item.id === reservation?.primaryGuestId); const room = state.rooms.find((item) => item.id === reservation?.roomId); const hasDebt = Boolean(reservation?.balance); const paymentHref = reservation ? `/admin/pagos/nuevo?reservation=${reservation.id}&returnTo=${encodeURIComponent(`/admin/check-out?reservation=${reservation.id}`)}` : "/admin/pagos/nuevo";
  async function submit(event: FormEvent) { event.preventDefault(); try { if (!canManage) throw new Error("No tenés permiso para realizar check-out."); if (!reservation) throw new Error("Seleccioná una estadía alojada."); if (hasDebt) throw new Error("La reserva debe quedar sin saldo pendiente antes del check-out."); await checkOut(reservation.id); router.push("/admin/operacion?checked=out"); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible hacer el check-out."); } }
  return <><AdminPageHeader eyebrow="Salidas · límite 10:00" title="Hacer check-out" description="Cierra la estadía y envía automáticamente la habitación a limpieza." /><div className="admin-operation-layout"><form className="admin-form-card" onSubmit={submit}><label className="admin-select-record">Estadía alojada<select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}><option value="">Seleccionar estadía</option>{eligible.map((item) => { const person = state.guests.find((guestItem) => guestItem.id === item.primaryGuestId); return <option value={item.id} key={item.id}>{item.code} · {person ? formatGuestName(person.firstName, person.lastName) : "Sin huésped"}</option>; })}</select></label>{reservation && guest ? <div className="admin-operation-card"><div className="admin-operation-card__hero"><span>{guest.firstName.slice(0,1)}</span><div><p>Huésped principal</p><h2>{formatGuestName(guest.firstName, guest.lastName)}</h2><small>{room?.displayName}</small></div></div><dl><div><dt>Salida prevista</dt><dd>{formatDate(reservation.checkOut)}</dd></div><div><dt>Hora límite</dt><dd>10:00 hs</dd></div><div><dt>Total</dt><dd>{formatCurrency(reservation.total)}</dd></div><div><dt>Pagado</dt><dd>{formatCurrency(reservation.paid)}</dd></div><div><dt>Saldo</dt><dd>{formatCurrency(reservation.balance)}</dd></div></dl>{hasDebt ? <div className="admin-debt-warning"><StatusPill status="alert">Saldo pendiente</StatusPill><strong>Esta reserva tiene un saldo pendiente de {formatCurrency(reservation.balance)}.</strong><Link className="admin-button admin-button--compact" href={paymentHref}>Registrar pago</Link></div> : <p className="admin-success-note">La estadía no tiene saldo pendiente y puede cerrarse.</p>}</div> : null}{!state.rooms.length ? <p className="admin-form-error" role="alert">Todavía no hay habitaciones configuradas. Completá el inventario desde Configuración.</p> : !eligible.length ? <p className="admin-form-error" role="status">No hay estadías alojadas para cerrar.</p> : null}{!canManage ? <p className="admin-form-error" role="alert">Tu usuario puede consultar, pero no realizar check-out.</p> : null}{error ? <p className="admin-form-error" role="alert">{error}</p> : null}<button className="admin-button admin-button--primary admin-button--large" disabled={!reservation || hasDebt || !canManage} type="submit">Hacer check-out</button></form><aside className="admin-operation-help"><p>Al confirmar</p><ol><li>Se registra la salida real y se cierra la ocupación.</li><li>La asignación deja de estar activa.</li><li>La habitación pasa a pendiente de limpieza.</li><li>Se crea una tarea de limpieza y se conserva auditoría.</li></ol><small>Una habitación nunca queda disponible automáticamente después del check-out.</small></aside></div></>;
}
