"use client";

import { useState, type FormEvent } from "react";
import { useOperations } from "../components/operations-provider";
import { AdminPageHeader } from "../components/ui";
import type { InternalNote } from "../lib/types";

export default function NotesPage() {
  const { state, addNote } = useOperations(); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [form, setForm] = useState<{ entityType: InternalNote["entityType"]; entityId: string; text: string }>({ entityType: "general", entityId: "", text: "" });
  function submit(event: FormEvent) { event.preventDefault(); try { addNote({ entityType: form.entityType, entityId: form.entityId || undefined, text: form.text }); setForm({ ...form, text: "" }); setError(""); setMessage("Nota interna agregada al entorno de prueba."); } catch (caught) { setMessage(""); setError(caught instanceof Error ? caught.message : "No fue posible guardar la nota."); } }
  return <><AdminPageHeader eyebrow="Comunicación interna" title="Notas del equipo" description="Contexto operativo vinculado a huéspedes, reservas, habitaciones u otras entidades. Nunca se muestra en la web pública." /><div className="admin-notes-layout"><form className="admin-form-card" onSubmit={submit}><div className="admin-field-grid"><label>Vincular a<select value={form.entityType} onChange={(e) => setForm({ ...form, entityType: e.target.value as InternalNote["entityType"] })}><option value="general">Operación general</option><option value="guest">Huésped</option><option value="reservation">Reserva</option><option value="room">Habitación</option><option value="payment">Pago</option><option value="issue">Incidencia</option></select></label><label>Identificador <small>opcional</small><input value={form.entityId} onChange={(e) => setForm({ ...form, entityId: e.target.value })} placeholder="Ej. DEMO-RES-B" /></label><label className="admin-field--full">Nota<textarea required rows={5} value={form.text} onChange={(e) => setForm({ ...form, text: e.target.value })} placeholder="Información que debe conocer el próximo turno…" /></label></div>{message ? <p className="admin-feedback">{message}</p> : null}{error ? <p className="admin-form-error">{error}</p> : null}<button className="admin-button admin-button--primary" type="submit">Agregar nota interna</button></form><section className="admin-note-feed"><div className="admin-panel__heading"><div><p>Más recientes</p><h2>Registro de notas</h2></div><span className="admin-count">{state.notes.length}</span></div>{state.notes.map((note) => <article key={note.id}><div><span>{note.entityType}</span><time>{new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(note.createdAt))}</time></div><p>{note.text}</p><small>{note.author}</small></article>)}</section></div></>;
}
